name: Format, check, and test Go SDK

on:
  workflow_call:
    inputs:
      is-release:
        default: false
        type: boolean
        description: Whether this is a release run or not.

jobs:
  check-format-test-go-sdk:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.23']

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install just
        uses: extractions/setup-just@v3

      - name: Install dependencies
        run: |
          just install-deps

      - name: Lint with golint
        run: |
          just lint

      - name: Check formatting with gofmt
        run: |
          just fmt-check

      - name: Run tests with ginkgo
        run: |
          just test-coverage-ci

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/src_realitydefender_coverprofile.out
          flags: go
          name: go-sdk-codecov
          fail_ci_if_error: true
