name: Build and Publish Go SDK

on:
  workflow_run:
    workflows: ["Test Go SDK"]
    types:
      - completed
    branches: [main]

jobs:
  publish-go-sdk:
    # Only run if the test workflow succeeded and this is on the main branch
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: main
    
    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}
        
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
        
    - name: Install dependencies
      run: go mod download
        
    - name: Build package
      run: go build -v ./...
      
    - name: Tag version
      id: tag_version
      run: |
        VERSION=$(grep -m 1 "go [0-9]\+\.[0-9]\+\.[0-9]\+" go.mod | sed 's/.*go \([0-9.]*\).*/\1/')
        COMMIT_SHORT=$(git rev-parse --short HEAD)
        TAG_NAME="v${VERSION}"
        echo "VERSION=${TAG_NAME}" >> $GITHUB_OUTPUT
        git config --local user.email "github-actions@github.com"
        git config --local user.name "GitHub Actions"
        git tag -a "${TAG_NAME}" -m "v${TAG_NAME}"
        git push origin "${TAG_NAME}"
        
    - name: Push to Go proxy
      run: |
        # Force the Go proxy to recognize the new version
        GOPROXY=proxy.golang.org go list -m github.com/Reality-Defender/realitydefender-sdk-go@${{ steps.tag_version.outputs.VERSION }}
